apiVersion: v1
kind: Service
metadata:
  name: monitoring-heapster
  labels:
    name: kubernetes.io/cluster-service=true
    name: monitoring-heapster
spec:
  clusterIP: 10.0.202.206
  ports: 
    - port: 8080
      protocol: TCP
  selector:
    k8s-app: heapster
  type: LoadBalancer
